version: '3'

services:
  hello-world:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:8080
  site:
    image: php:apache
    volumes:
      - ./site:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - hello-world

